### ISSUE TITLE
Duplicate buffer output

### ISSUE THREAD

**Issue by johnaohara** [RedHatPerf/qDup#31]
For some scripts, the buffer output is dupliated;

e.g. 
[[[[INFOO]  Building benchmark-parent 1.0.0.Alpha1-SNAPSHOT                    [1/6]]
[[[[INFOO] --------------------------------[ pom ]---------------------------------
[[INFO] 
[[[[[INFO]    --- maven-clean-plugin:3.0.0:clean (default-clean)) @   benchmark-parent ---
[INFO] 
[[[[[INFO]   ---    maven-enforcer-plugin:3.0.0-M1:enforce (enforce-java-version) @ benchmark-parent ---
[[INFO] 
[[[[[INFO] --- maven-enforcer-plugin:3.0.0-M1:enforcee (enforce-maven-version)) @ benchmark-parentntntnt -----

**Comment by johnaohara** [comment]
User error ;) had run same script under multiple users on same host

**Comment by johnaohara** [comment]
Still outputting multiple chars from buffer, even though there is only on script per host

**Comment by willr3** [comment]
I would suspect this is an off by one issue with how the OutputStreams buffer and write to the downstream buffers. SshSession.connect is responsible for creating the OutputStreams and chaining them appropriately. The current design is Apache Ssh -> EscapeFilteredStream -> SuffixStream -> FilteredStream -> ByteArrayOutputStream.
EscapeFilteredStream removes the terminal escapes (curors moves and screan clears)
SuffixStream looks for the prompt at the end if the write to determine when the current command finished
FilteredStream removes output that we don't want to assume came from the current command. This includes the prompt, the command itself being echo'd back from the connection, 
ByteArrayOutputStream stores the output from the FilteredStream for each command
Each of the above Streams (except BAOS) copies writes into an internal buffer then scans the buffer before passing data to the next stream. The problem is likely with how one of those buffers is maintaining it's writeIndex.

**Comment by willr3** [comment]
I was wrong, the issue was with EscapeFilteredStream removing terminal escape sequences from the start and end of a write(byte[],#,#) call but not correctly shifting the buffered bytes. I added EscapeFilteredStreamTest.issue31_duplicate_buffer() based on the calls to write that I saw when running the yaml
